import React from 'react';

export const SeoContent: React.FC = () => {
  return (
    <article className="prose prose-slate max-w-none bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
      <header className="mb-6">
        <h2 className="text-2xl font-bold text-slate-900">How to Calculate LLM API Costs for Your SaaS</h2>
      </header>
      
      <p>
        Building an AI-powered application requires careful financial planning. The unit economics of Generative AI can be complex because pricing models are based on "tokens" rather than traditional API calls.
      </p>

      <h3 className="text-xl font-semibold text-slate-800 mt-6 mb-3">Understanding the Formula</h3>
      <p>
        To accurately estimate your monthly spend, you need to understand four key variables:
      </p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Monthly Active Users (MAU):</strong> The number of unique users interacting with your tool.</li>
        <li><strong>Interaction Frequency:</strong> How many times per day does an average user make a request?</li>
        <li><strong>Input Tokens:</strong> The length of the text sent to the model (User prompt + System instructions + Context).</li>
        <li><strong>Output Tokens:</strong> The length of the text generated by the model. These are typically more expensive than input tokens.</li>
      </ul>

      <h3 className="text-xl font-semibold text-slate-800 mt-6 mb-3">Why Token Pricing Matters</h3>
      <p>
        Different models have vastly different cost structures. For example, <strong>GPT-4o</strong> offers reasoning capabilities at a higher price point, while <strong>Gemini 1.5 Flash</strong> or <strong>GPT-4o Mini</strong> provide extremely cost-effective solutions for high-volume tasks.
      </p>
      <p>
        A startup with 10,000 MAUs sending long prompts might spend $500/month on one model and $5,000/month on another. This calculator helps you visualize those differences instantly so you can choose the right model for your business margins.
      </p>
    </article>
  );
};